esphome:
  name: dubica
  friendly_name: dubica
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:
  # level: VERY_VERBOSE
api:
  encryption:
    key: "N7NsSDPdeu2QfPpC0EKIKaw9rzUgOFZ2OQBQZ7+f6lQ="

ota:
  password: "70bec50222d4656fde384649e37d8a43"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Dubica Fallback Hotspot"
    password: "HJjTZMs4jTRE"

captive_portal:

# Настройка выключателей света и воды
switch:
  - platform: gpio
    id: light
    name: "Light 1"
    pin: 2
  - platform: gpio
    id: water1
    name: "Water 1"
    pin: 13
  - platform: gpio
    id: water2
    name: "Water 2"
    pin:
      number: 27
  - platform: gpio
    id: water3
    name: "Water 3"
    pin:
      number: 32
  - platform: gpio
    id: open_cover_switch
    internal: true
    pin: 27
  - platform: gpio
    id: close_cover_switch
    internal: true
    pin: 27

i2c:
  sda: 21
  scl: 22
  frequency: 200kHz

# Кнопка энкодера
binary_sensor:
  - platform: gpio
    internal: true
    name: "menu_push"
    pin:
      number: 39
      inverted: true
    on_press:
      - display_menu.enter:
# Крутелка энкодера
sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    internal: true
    pin_a: 35
    pin_b: 34
    on_anticlockwise:
      - display_menu.up:
    on_clockwise:
      - display_menu.down:

# Окна, пока закоменчены, чет валят всю систему
# - platform: gpio
#   internal: true
#   id: open_endstop_binary_sensor
#   pin:
#     number: 2
#     inverted: true
# - platform: gpio
#   internal: true
#   id: close_endstop_binary_sensor
#   pin:
#     number: 2
#     inverted: true
# - platform: gpio
#   internal: true
#   id: open_movement_binary_sensor
#   pin:
#     number: 2
#     inverted: true
# - platform: gpio
#   internal: true
#   id: close_movement_binary_sensor
#   pin:
#     number: 2
#     inverted: true

# cover:
#   - platform: feedback
#     name: "Gate"

#     open_action:
#       - switch.turn_on: open_cover_switch
#     open_duration: 120sec
#     open_endstop: open_endstop_binary_sensor
#     open_sensor: open_movement_binary_sensor

#     close_action:
#       - switch.turn_on: close_cover_switch
#     close_duration: 100sec
#     close_endstop: close_endstop_binary_sensor
#     close_sensor: close_movement_binary_sensor

#     stop_action:
#       - switch.turn_off: open_cover_switch
#       - switch.turn_off: close_cover_switch

# Настройки экрана и кирилицы
display:
  - platform: lcd_pcf8574
    id: my_lcd
    update_interval: 0.2s
    dimensions: 20x4
    address: 0x27
    lambda: |-
      id(my_lcd_menu).draw();
      if (!id(my_lcd_menu).is_active())
        it.print("Menu is not active");
    user_characters:
      # https://omerk.github.io/lcdchargen/
      # Буква П
      - position: 0
        data:
          - 0b11111
          - 0b10001
          - 0b10001
          - 0b10001
          - 0b10001
          - 0b10001
          - 0b10001
          - 0b00000
      # Буква У
      - position: 1
        data:
          - 0b10001
          - 0b10001
          - 0b10001
          - 0b01010
          - 0b00100
          - 0b01000
          - 0b10000
          - 0b00000
      # Буква Д
      - position: 2
        data:
          - 0b00111
          - 0b00101
          - 0b00101
          - 0b01001
          - 0b01001
          - 0b01001
          - 0b11111
          - 0b10001
      # Буква Л
      - position: 3
        data:
          - 0b00111
          - 0b00101
          - 0b00101
          - 0b01001
          - 0b01001
          - 0b01001
          - 0b01001
          - 0b00000
      # Буква Ы
      - position: 4
        data:
          - 0b10001
          - 0b10001
          - 0b10001
          - 0b11101
          - 0b10101
          - 0b10101
          - 0b11101
          - 0b00000

# Настройка меню
lcd_menu:
  id: my_lcd_menu
  display_id: my_lcd
  active: true
  mode: rotary
  on_enter:
    then:
      lambda: 'ESP_LOGI("display_menu", "root enter");'
  on_leave:
    then:
      lambda: 'ESP_LOGI("display_menu", "root leave");'
  items:
    - type: label
      text: "TEM\x08EPAT\x01PA: 35"
    - type: label
      text: "OKHA"

    - type: switch
      text: "CBET"
      immediate_edit: true
      on_text: "BK\x03"
      off_text: "B\x04K\x03"
      switch: light

    - type: switch
      text: "BO\x02A 1"
      immediate_edit: true
      on_text: "BK\x03"
      off_text: "B\x04K\x03"
      switch: water1

    - type: switch
      text: "BO\x02A 2"
      immediate_edit: true
      on_text: "BK\x03"
      off_text: "B\x04K\x03"
      switch: water2

    - type: switch
      text: "BO\x02A 3"
      immediate_edit: true
      on_text: "BK\x03"
      off_text: "B\x04K\x03"
      switch: water3
